# testing changes
sudo: required
services:
  - docker

before_install:
  - docker build -t jeffligon/docker-react -f Dockerfile.dev .

script:
  - docker run jeffligon/docker-react npm run test -- --coverage