#  changed --coverage to -e CI=true -- --watchAll=false
#  as suggested in Q&A, so that 'npm run test' ends with exit code 0
sudo: required
services:
  - docker

before_install:
  - docker build -t jeffligon/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jeffligon/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: docker-react
  env: DockerReact-env
# To find bucket_name, search S3 buckets, look for "elasticbeanstalk"  
  bucket_name: "elasticbeanstalk-us-east-2-765735861180"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"